import { Participant } from "@/shared/types"

export const participants: Participant[] = [
  {
    id: "6051318015",
    name: "Eal Nottle",
    email: "enottle0@php.net",
    github: "enottle0",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "3494260686",
    name: "Sibyl Spence",
    email: "sspence1@surveymonkey.com",
    github: "sspence1",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "9566202070",
    name: "Shari Coan",
    email: "scoan2@hibu.com",
    github: "scoan2",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "5491035706",
    name: "Sheena Bend",
    email: "sbend3@blogger.com",
    github: "sbend3",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "0027457519",
    name: "Bartlet Boote",
    email: "bboote4@utexas.edu",
    github: "bboote4",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "8197850668",
    name: "Jourdan Kemson",
    email: "jkemson5@wikimedia.org",
    github: "jkemson5",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "4739706055",
    name: "Rudy McGoon",
    email: "rmcgoon6@walmart.com",
    github: "rmcgoon6",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "6167293158",
    name: "Katalin Grief",
    email: "kgrief7@techcrunch.com",
    github: "kgrief7",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "4548235061",
    name: "Tuckie Hartzenberg",
    email: "thartzenberg8@who.int",
    github: "thartzenberg8",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "6959175710",
    name: "Gabby Sivior",
    email: "gsivior9@slate.com",
    github: "gsivior9",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "9350462303",
    name: "Bliss Madgwich",
    email: "bmadgwicha@webmd.com",
    github: "bmadgwicha",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "2870307747",
    name: "Shaylah Wetherell",
    email: "swetherellb@forbes.com",
    github: "swetherellb",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "5305026624",
    name: "Barnie Chsteney",
    email: "bchsteneyc@wix.com",
    github: "bchsteneyc",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "1268677280",
    name: "Orlan Beamond",
    email: "obeamondd@businesswire.com",
    github: "obeamondd",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "6072344282",
    name: "Jacinta McKevin",
    email: "jmckevine@tripod.com",
    github: "jmckevine",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "9944429562",
    name: "Hasheem Teers",
    email: "hteersf@163.com",
    github: "hteersf",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "4715646448",
    name: "Wernher Grim",
    email: "wgrimg@jalbum.net",
    github: "wgrimg",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "5118963854",
    name: "Nelia Tambling",
    email: "ntamblingh@sciencedirect.com",
    github: "ntamblingh",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "7256456855",
    name: "Tore Cumberlidge",
    email: "tcumberlidgei@ed.gov",
    github: "tcumberlidgei",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "9912326576",
    name: "Carmelle Padson",
    email: "cpadsonj@cmu.edu",
    github: "cpadsonj",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "3102711916",
    name: "Prent Stannett",
    email: "pstannettk@vinaora.com",
    github: "pstannettk",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "1486939014",
    name: "Jennine Cundict",
    email: "jcundictl@last.fm",
    github: "jcundictl",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "2848954913",
    name: "Micaela Ebbotts",
    email: "mebbottsm@etsy.com",
    github: "mebbottsm",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "6936926411",
    name: "Case Wilsher",
    email: "cwilshern@seesaa.net",
    github: "cwilshern",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "3398121175",
    name: "Rubia Nielson",
    email: "rnielsono@ustream.tv",
    github: "rnielsono",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "1111389807",
    name: "Darn Agget",
    email: "daggetp@51.la",
    github: "daggetp",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "9622596294",
    name: "Lottie Gilligan",
    email: "lgilliganq@princeton.edu",
    github: "lgilliganq",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "9776624499",
    name: "Brucie Pollock",
    email: "bpollockr@shop-pro.jp",
    github: "bpollockr",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "1061755757",
    name: "Laina Cripin",
    email: "lcripins@dedecms.com",
    github: "lcripins",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "2911567510",
    name: "Garth Padmore",
    email: "gpadmoret@exblog.jp",
    github: "gpadmoret",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "3618011368",
    name: "Madlin Boler",
    email: "mboleru@microsoft.com",
    github: "mboleru",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "2653233106",
    name: "Timmy Cobden",
    email: "tcobdenv@360.cn",
    github: "tcobdenv",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "0696623800",
    name: "Ingaborg Ashfold",
    email: "iashfoldw@telegraph.co.uk",
    github: "iashfoldw",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "0112716260",
    name: "Mitzi Rollett",
    email: "mrollettx@ocn.ne.jp",
    github: "mrollettx",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "4592696363",
    name: "Keriann Spellworth",
    email: "kspellworthy@stumbleupon.com",
    github: "kspellworthy",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "5196302623",
    name: "Donovan Hucquart",
    email: "dhucquartz@github.com",
    github: "dhucquartz",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "3775446162",
    name: "Saba Klaassens",
    email: "sklaassens10@nytimes.com",
    github: "sklaassens10",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "7517431683",
    name: "Niki Penella",
    email: "npenella11@kickstarter.com",
    github: "npenella11",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "3667209386",
    name: "Gerda Moxsom",
    email: "gmoxsom12@guardian.co.uk",
    github: "gmoxsom12",
    wannaPlay: true,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
  {
    id: "1162164608",
    name: "Dion Jakubiak",
    email: "djakubiak13@prlog.org",
    github: "djakubiak13",
    wannaPlay: false,
    gonnaPlay: false,
    winner: false,
    groupId: null,
  },
]
